### ISSUE TITLE
References/Relations to user groups

### ISSUE THREAD

**Issue by Idered** [Syncano/orion#40]
Currently `users` class can be referenced but user groups can't. It would be cool to use them like the rest of classes

```yaml
class:
  member:
    - name:  groups
       type: relation
       target: user_groups
```

```js
data.member.with('groups').list()
```

```json
[
  {
    "id": 1,
    "groups": [
       {
         "id": 1,
         "name": "admin",
         "label": "Admin",
         "description": "",
       }
     ] 
  }
]
```
